AllCops:
  Exclude:
    - db/schema.rb
    - vendor/bundle/**/*

  Include:
    - '**/*.builder'
    - '**/*.jbuilder'
    - '**/*.rake'
    - '**/config.ru'
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/Capfile'
    - '**/Vagrantfile'

  DisplayCopNames: true

  DisplayStyleGuide: true

Metrics:
  Enabled: false

Performance/Casecmp:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Style/ModuleFunction:
  EnforcedStyle: extend_self

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '[]'
    '%w': '[]'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/EmptyMethod:
  EnforcedStyle: expanded

Rails:
  Enabled: true

Rails/UnknownEnv:
  Environments:
    - development
    - production
    - staging
    - test
