---
connection: &connection
  adapter: postgresql
  timeout: 5000
  pool: 25
development:
  database: nolotirov3_dev
  pool: 5
  <<: *connection
test:
  database: nolotirov3_test
  pool: 5
  <<: *connection
staging:
  url: <%= ENV['DATABASE_URL'] %>
production:
  url: <%= ENV['DATABASE_URL'] %>
