# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies. If you
# change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random, no regular
# words or you'll be exposed to dictionary attacks. You can use `rails secret`
# to generate a secure secret key.

# Make sure the secrets in this file are kept private if you're sharing your
# code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

defaults: &defaults
  secret_token: <%= ENV['NLT_SECRET_TOKEN'] %>
  secret_key_base: <%= ENV['NLT_SECRET_KEY_BASE'] %>
  smtp_address: <%= ENV['SMTP_ADDRESS'] || "localhost" %>
  smtp_port: <%= ENV['SMTP_PORT'] || "25" %>
  smtp_authentication: <%= ENV['SMTP_AUTHENTICATION'] || "none" %>
  smtp_username: <%= ENV['SMTP_USER'] %>
  smtp_password: <%= ENV['SMTP_PASS'] %>
  smtp_domain: <%= ENV['SMTP_DOMAIN'] %>
  smtp_starttls_auto: <%= ENV['SMTP_STARTTLS_AUTO'] || "true" %>

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
